import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Lato } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  // weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Wings & Things",
  description: "Generated by create next app",
  icons: {
    icon:"/favicon-32x32.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon-32x32.png" sizes="any" />
      </head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
